language: node_js
node_js:
    - "6"
script:
    - npm run test # first run tests, to fail quickly.
    - npm run build
notifications:
    email: false
branches:
    only:
    - gsoc-ci
    - /^test-.*$/
